# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-03-04 16:12:39
"""
import arcpy

def flooding():  # Flooding Analysis

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    floodzones = "floodzones"
    basin = "basin"

    # Process: Clip (Clip) (analysis)
    floodzones_Clip = "C:\\ProgrammingProjects\\GISC2335_ProgrammingForGIS\\WeeklyContent\\week4\\data\\Ex03\\Study.gdb\\floodzones_Clip"
    arcpy.analysis.Clip(in_features=floodzones, clip_features=basin, out_feature_class=floodzones_Clip)

    # Process: Select (Select) (analysis)
    flooding = "C:\\ProgrammingProjects\\GISC2335_ProgrammingForGIS\\WeeklyContent\\week4\\data\\Ex03\\Study.gdb\\flooding"
    arcpy.analysis.Select(in_features=floodzones_Clip, out_feature_class=flooding, where_clause="SFHA = 'IN'")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\ProgrammingProjects\\GISC2335_ProgrammingForGIS\\WeeklyContent\\week4\\data\\Ex03\\Study.gdb", workspace="C:\\ProgrammingProjects\\GISC2335_ProgrammingForGIS\\WeeklyContent\\week4\\data\\Ex03\\Study.gdb"):
        flooding()
